delete from public.cars where id < 550;

insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (1, 'audi', 'e36', 1.3, 'COUPE', 'ELECTRIC', 921999, 1985);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (2, 'opel', 'amg63', 1.7, 'COUPE', 'BENZINE', 771561, 1992);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (3, 'skoda', 'e47', 1.1, 'STATION_WAGON', 'DIESEL', 982522, 2012);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (4, 'mercedes', 'a7', 1.8, 'STATION_WAGON', 'BENZINE', 779799, 2006);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (5, 'bmw', 'insignia', 1.3, 'SEDAN', 'DIESEL', 559039, 1995);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (6, 'skoda', 'insignia', 1.1, 'CABRIOLET', 'LPG', 154435, 1995);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (7, 'audi', 'fabia', 1.6, 'HATCHBACK', 'LPG', 807970, 1986);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (8, 'opel', 'a7', 1.8, 'STATION_WAGON', 'ELECTRIC', 151759, 1983);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (9, 'wolkswagen', 'a7 avant', 1.6, 'COUPE', 'LPG', 130106, 2011);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (10, 'audi', 'g62', 1.0, 'COUPE', 'ELECTRIC', 526624, 2007);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (11, 'mercedes', 'amg63', 1.5, 'HATCHBACK', 'DIESEL', 120974, 2005);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (12, 'wolkswagen', 'insignia', 1.1, 'STATION_WAGON', 'LPG', 718173, 2006);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (13, 'opel', 'a4b7', 1.3, 'SEDAN', 'LPG', 331184, 1994);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (14, 'mercedes', 'insignia', 1.2, 'COUPE', 'BENZINE', 906767, 2008);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (15, 'mercedes', 'fabia', 1.2, 'HATCHBACK', 'ELECTRIC', 611360, 2006);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (16, 'bmw', 'a7', 1.1, 'STATION_WAGON', 'BENZINE', 829951, 2001);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (17, 'wolkswagen', 'f26', 1.5, 'STATION_WAGON', 'ELECTRIC', 711510, 1996);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (18, 'opel', 'octavia', 1.4, 'SUV', 'BENZINE', 623231, 2011);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (19, 'mercedes', 'insignia', 1.6, 'HATCHBACK', 'LPG', 132390, 1999);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (20, 'bmw', 'a7', 1.3, 'HATCHBACK', 'LPG', 358159, 2008);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (21, 'mercedes', 'octavia', 1.5, 'STATION_WAGON', 'ELECTRIC', 849077, 2003);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (22, 'opel', 'insignia', 1.6, 'CABRIOLET', 'DIESEL', 83972, 2005);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (23, 'wolkswagen', 'octavia', 1.8, 'HATCHBACK', 'DIESEL', 248576, 2000);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (24, 'audi', 'octavia', 1.6, 'SEDAN', 'BENZINE', 192559, 1991);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (25, 'opel', 'a4b5', 1.2, 'SEDAN', 'DIESEL', 477646, 2001);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (26, 'wolkswagen', 'c63amg', 1.8, 'CABRIOLET', 'ELECTRIC', 979004, 1992);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (27, 'bmw', 'f26', 1.6, 'COUPE', 'DIESEL', 576033, 2001);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (28, 'bmw', 'e36', 1.3, 'HATCHBACK', 'BENZINE', 706460, 1968);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (29, 'mercedes', 'e47', 1.9, 'STATION_WAGON', 'ELECTRIC', 429854, 1990);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (30, 'wolkswagen', 'amg63', 1.2, 'COUPE', 'ELECTRIC', 623658, 1992);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (31, 'skoda', 'amg63', 1.4, 'COUPE', 'LPG', 837347, 2002);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (32, 'opel', 'passat b5', 1.8, 'SUV', 'LPG', 464653, 1994);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (33, 'wolkswagen', 'fabia', 1.1, 'HATCHBACK', 'BENZINE', 672348, 2000);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (34, 'audi', 'arteon', 1.6, 'COUPE', 'BENZINE', 970908, 1985);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (35, 'bmw', 'passat b5', 1.6, 'STATION_WAGON', 'BENZINE', 392566, 2009);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (36, 'wolkswagen', 'a4b7', 1.2, 'STATION_WAGON', 'ELECTRIC', 252495, 2005);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (37, 'audi', 'insignia', 1.7, 'SUV', 'BENZINE', 118593, 2009);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (38, 'bmw', 'fabia', 1.9, 'CABRIOLET', 'DIESEL', 500515, 1926);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (39, 'opel', 'insignia', 1.3, 'SUV', 'DIESEL', 632416, 2009);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (40, 'mercedes', 'f26', 1.5, 'COUPE', 'DIESEL', 377161, 2006);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (41, 'opel', 'a7 avant', 1.9, 'SEDAN', 'DIESEL', 230014, 1995);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (42, 'bmw', 'e36', 1.2, 'SUV', 'ELECTRIC', 499672, 2008);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (43, 'opel', 'a4b7', 1.7, 'HATCHBACK', 'BENZINE', 80514, 2008);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (44, 'opel', 'a8', 1.8, 'SUV', 'DIESEL', 725194, 2000);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (45, 'opel', 'e36', 1.3, 'COUPE', 'DIESEL', 429725, 2001);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (46, 'wolkswagen', 'e47', 1.8, 'SUV', 'DIESEL', 580125, 2009);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (47, 'wolkswagen', 'octavia', 2.0, 'STATION_WAGON', 'LPG', 917379, 2008);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (48, 'skoda', 'fabia', 1.8, 'HATCHBACK', 'ELECTRIC', 534384, 1993);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (49, 'wolkswagen', 'a8', 1.6, 'CABRIOLET', 'DIESEL', 926042, 2006);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (50, 'wolkswagen', 'f26', 1.8, 'SEDAN', 'BENZINE', 149810, 1992);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (51, 'mercedes', 'fabia', 1.3, 'CABRIOLET', 'LPG', 111480, 1993);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (52, 'bmw', 'e47', 1.4, 'SEDAN', 'BENZINE', 310639, 1992);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (53, 'skoda', 'a7 avant', 1.0, 'SUV', 'DIESEL', 203252, 2003);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (54, 'opel', 'a7', 1.2, 'HATCHBACK', 'LPG', 451575, 2002);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (55, 'opel', 'amg63', 1.4, 'SEDAN', 'DIESEL', 762173, 1977);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (56, 'opel', 'a8', 1.5, 'CABRIOLET', 'ELECTRIC', 700227, 1991);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (57, 'wolkswagen', 'passat b5', 1.9, 'STATION_WAGON', 'ELECTRIC', 721583, 2011);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (58, 'bmw', 'e36', 1.5, 'CABRIOLET', 'BENZINE', 962577, 2010);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (59, 'audi', 'insignia', 1.5, 'HATCHBACK', 'BENZINE', 614157, 1997);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (60, 'mercedes', 'amg63', 1.4, 'CABRIOLET', 'ELECTRIC', 261667, 1994);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (61, 'mercedes', 'e47', 1.4, 'SEDAN', 'BENZINE', 117302, 2012);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (62, 'mercedes', 'g62', 1.5, 'SUV', 'ELECTRIC', 666297, 1992);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (63, 'skoda', 'c63amg', 1.3, 'HATCHBACK', 'LPG', 505752, 1994);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (64, 'opel', 'a7', 1.2, 'SEDAN', 'DIESEL', 91015, 2012);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (65, 'wolkswagen', 'a8', 1.4, 'STATION_WAGON', 'ELECTRIC', 315629, 2010);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (66, 'bmw', 'a8', 1.8, 'COUPE', 'DIESEL', 435994, 1964);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (67, 'opel', 'a4b7', 1.6, 'CABRIOLET', 'ELECTRIC', 403409, 2001);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (68, 'wolkswagen', 'c63amg', 1.6, 'HATCHBACK', 'DIESEL', 764055, 1998);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (69, 'bmw', 'arteon', 1.7, 'STATION_WAGON', 'LPG', 357817, 2012);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (70, 'bmw', 'e47', 1.5, 'SEDAN', 'DIESEL', 365874, 2003);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (71, 'audi', 'c63amg', 1.9, 'SUV', 'ELECTRIC', 506732, 1983);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (72, 'opel', 'e47', 1.8, 'HATCHBACK', 'BENZINE', 239096, 2006);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (73, 'mercedes', 'a7', 1.6, 'COUPE', 'ELECTRIC', 661976, 2010);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (74, 'opel', 'fabia', 1.9, 'STATION_WAGON', 'BENZINE', 374719, 1995);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (75, 'audi', 'a4b5', 1.6, 'COUPE', 'LPG', 703894, 2011);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (76, 'bmw', 'insignia', 1.5, 'COUPE', 'BENZINE', 688043, 2004);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (77, 'opel', 'passat b5', 1.3, 'SUV', 'BENZINE', 210921, 1990);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (78, 'mercedes', 'arteon', 1.9, 'CABRIOLET', 'ELECTRIC', 578102, 2002);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (79, 'wolkswagen', 'c63amg', 1.1, 'HATCHBACK', 'LPG', 238071, 1976);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (80, 'bmw', 'a7 avant', 1.4, 'STATION_WAGON', 'DIESEL', 137448, 1985);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (81, 'skoda', 'a7', 2.0, 'COUPE', 'LPG', 527807, 1995);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (82, 'opel', 'a4b5', 1.7, 'COUPE', 'BENZINE', 255851, 2011);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (83, 'wolkswagen', 'a5c6', 1.4, 'HATCHBACK', 'BENZINE', 537035, 2011);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (84, 'mercedes', 'a7', 1.2, 'SUV', 'LPG', 758017, 2004);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (85, 'mercedes', 'amg63', 1.2, 'HATCHBACK', 'LPG', 476668, 1994);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (86, 'skoda', 'g62', 1.6, 'SUV', 'DIESEL', 493559, 2006);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (87, 'opel', 'a8', 1.8, 'HATCHBACK', 'DIESEL', 275074, 1994);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (88, 'mercedes', 'amg63', 1.8, 'CABRIOLET', 'LPG', 974571, 1992);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (89, 'wolkswagen', 'a7', 1.4, 'HATCHBACK', 'BENZINE', 293640, 2005);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (90, 'opel', 'fabia', 1.8, 'COUPE', 'ELECTRIC', 210094, 1997);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (91, 'mercedes', 'a4b5', 1.7, 'SUV', 'BENZINE', 568429, 1994);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (92, 'wolkswagen', 'a8', 1.8, 'SUV', 'DIESEL', 518795, 2004);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (93, 'wolkswagen', 'passat b5', 1.9, 'CABRIOLET', 'LPG', 815056, 2010);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (94, 'opel', 'amg63', 1.7, 'SEDAN', 'LPG', 263952, 1994);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (95, 'opel', 'g62', 1.9, 'CABRIOLET', 'DIESEL', 125276, 1991);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (96, 'bmw', 'octavia', 1.9, 'SEDAN', 'ELECTRIC', 325303, 2010);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (97, 'wolkswagen', 'octavia', 1.7, 'STATION_WAGON', 'ELECTRIC', 865342, 2004);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (98, 'opel', 'a5c6', 1.6, 'CABRIOLET', 'ELECTRIC', 404616, 2001);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (99, 'mercedes', 'a8', 1.4, 'STATION_WAGON', 'LPG', 986634, 1999);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (100, 'wolkswagen', 'a4b7', 1.2, 'SEDAN', 'LPG', 750596, 2008);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (101, 'opel', 'insignia', 1.5, 'SEDAN', 'LPG', 630450, 1997);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (102, 'audi', 'amg63', 1.8, 'SUV', 'BENZINE', 540166, 1992);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (103, 'audi', 'fabia', 1.5, 'HATCHBACK', 'LPG', 528631, 1999);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (104, 'mercedes', 'a5c6', 1.5, 'HATCHBACK', 'ELECTRIC', 319042, 1990);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (105, 'skoda', 'e47', 1.8, 'SEDAN', 'DIESEL', 114279, 2007);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (106, 'skoda', 'g62', 1.1, 'SUV', 'ELECTRIC', 925182, 2010);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (107, 'skoda', 'e36', 1.5, 'COUPE', 'BENZINE', 255372, 1991);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (108, 'skoda', 'e36', 1.9, 'CABRIOLET', 'DIESEL', 195054, 2009);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (109, 'mercedes', 'e36', 1.2, 'COUPE', 'BENZINE', 216312, 2009);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (110, 'audi', 'passat b5', 1.6, 'COUPE', 'BENZINE', 981734, 2005);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (111, 'wolkswagen', 'a4b7', 1.8, 'CABRIOLET', 'DIESEL', 798565, 2008);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (112, 'audi', 'a8', 1.4, 'HATCHBACK', 'ELECTRIC', 563178, 1993);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (113, 'wolkswagen', 'octavia', 1.7, 'CABRIOLET', 'LPG', 847071, 2005);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (114, 'opel', 'arteon', 1.2, 'SUV', 'ELECTRIC', 138377, 2004);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (115, 'opel', 'a8', 1.8, 'COUPE', 'BENZINE', 791775, 1992);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (116, 'mercedes', 'a5c6', 1.4, 'COUPE', 'LPG', 331760, 1995);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (117, 'mercedes', 'a4b5', 1.3, 'SEDAN', 'ELECTRIC', 306054, 2009);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (118, 'audi', 'passat b5', 1.1, 'SEDAN', 'LPG', 544254, 2011);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (119, 'opel', 'a7', 1.8, 'COUPE', 'BENZINE', 163077, 2011);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (120, 'bmw', 'a7 avant', 1.7, 'HATCHBACK', 'LPG', 451250, 1998);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (121, 'bmw', 'g62', 1.7, 'SEDAN', 'LPG', 819848, 1999);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (122, 'mercedes', 'arteon', 1.7, 'STATION_WAGON', 'DIESEL', 799247, 1999);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (123, 'audi', 'passat b5', 1.1, 'SEDAN', 'DIESEL', 590761, 1986);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (124, 'audi', 'a7', 1.1, 'SEDAN', 'DIESEL', 955087, 1973);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (125, 'skoda', 'f26', 1.8, 'HATCHBACK', 'DIESEL', 935306, 2013);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (126, 'opel', 'f26', 1.1, 'SEDAN', 'LPG', 917834, 2005);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (127, 'bmw', 'a5c6', 1.8, 'CABRIOLET', 'BENZINE', 99165, 2008);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (128, 'wolkswagen', 'passat b5', 1.9, 'COUPE', 'ELECTRIC', 760849, 2011);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (129, 'skoda', 'a8', 1.1, 'HATCHBACK', 'BENZINE', 967597, 1987);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (130, 'bmw', 'a4b5', 1.5, 'CABRIOLET', 'LPG', 184280, 2002);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (131, 'bmw', 'a7 avant', 1.5, 'COUPE', 'ELECTRIC', 594004, 2001);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (132, 'opel', 'passat b5', 1.4, 'SEDAN', 'DIESEL', 369297, 1995);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (133, 'bmw', 'a4b7', 1.0, 'COUPE', 'LPG', 331180, 1993);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (134, 'mercedes', 'a5c6', 1.9, 'SEDAN', 'DIESEL', 415832, 1993);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (135, 'bmw', 'c63amg', 1.1, 'SUV', 'DIESEL', 331468, 1994);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (136, 'audi', 'fabia', 1.5, 'CABRIOLET', 'DIESEL', 759026, 2011);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (137, 'audi', 'e47', 1.1, 'HATCHBACK', 'ELECTRIC', 650618, 1988);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (138, 'mercedes', 'c63amg', 1.0, 'CABRIOLET', 'LPG', 171582, 1987);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (139, 'wolkswagen', 'g62', 1.6, 'SUV', 'BENZINE', 547222, 2006);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (140, 'skoda', 'amg63', 1.9, 'STATION_WAGON', 'DIESEL', 850043, 1987);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (141, 'bmw', 'e47', 1.4, 'COUPE', 'ELECTRIC', 120897, 2007);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (142, 'wolkswagen', 'g62', 2.0, 'CABRIOLET', 'DIESEL', 720935, 2012);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (143, 'audi', 'a5c6', 1.5, 'SUV', 'LPG', 674834, 1996);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (144, 'bmw', 'octavia', 1.7, 'SUV', 'ELECTRIC', 435142, 2009);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (145, 'audi', 'c63amg', 1.3, 'SUV', 'BENZINE', 856758, 2004);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (146, 'skoda', 'f26', 1.7, 'SUV', 'DIESEL', 474563, 2003);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (147, 'mercedes', 'octavia', 1.8, 'HATCHBACK', 'BENZINE', 932210, 2012);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (148, 'audi', 'insignia', 1.5, 'STATION_WAGON', 'LPG', 339331, 2011);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (149, 'mercedes', 'octavia', 1.4, 'COUPE', 'ELECTRIC', 829077, 2001);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (150, 'bmw', 'a7 avant', 1.4, 'SEDAN', 'DIESEL', 802159, 1992);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (151, 'skoda', 'a8', 1.0, 'STATION_WAGON', 'DIESEL', 83215, 2004);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (152, 'skoda', 'c63amg', 1.9, 'HATCHBACK', 'ELECTRIC', 547527, 2006);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (153, 'audi', 'a7 avant', 1.0, 'CABRIOLET', 'ELECTRIC', 498229, 1993);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (154, 'bmw', 'passat b5', 1.3, 'HATCHBACK', 'LPG', 808588, 2006);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (155, 'wolkswagen', 'amg63', 1.3, 'CABRIOLET', 'DIESEL', 220920, 1993);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (156, 'wolkswagen', 'octavia', 1.6, 'CABRIOLET', 'LPG', 391357, 1997);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (157, 'bmw', 'e36', 1.6, 'COUPE', 'LPG', 660817, 2006);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (158, 'skoda', 'e47', 1.5, 'COUPE', 'BENZINE', 662535, 2005);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (159, 'wolkswagen', 'a4b5', 1.9, 'COUPE', 'LPG', 735726, 1992);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (160, 'opel', 'arteon', 1.2, 'SUV', 'DIESEL', 378233, 1987);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (161, 'audi', 'e47', 1.3, 'SEDAN', 'BENZINE', 139983, 1994);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (162, 'audi', 'a4b7', 1.3, 'HATCHBACK', 'ELECTRIC', 888245, 1994);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (163, 'wolkswagen', 'a4b7', 1.0, 'SEDAN', 'ELECTRIC', 605099, 2011);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (164, 'opel', 'arteon', 1.6, 'CABRIOLET', 'BENZINE', 441414, 1999);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (165, 'audi', 'a7', 1.7, 'SUV', 'LPG', 874558, 2003);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (166, 'bmw', 'a4b5', 1.7, 'HATCHBACK', 'BENZINE', 836151, 1996);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (167, 'skoda', 'a4b5', 1.4, 'COUPE', 'LPG', 791204, 1996);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (168, 'skoda', 'e36', 1.8, 'COUPE', 'BENZINE', 917197, 2009);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (169, 'bmw', 'a5c6', 2.0, 'SUV', 'ELECTRIC', 329538, 2005);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (170, 'audi', 'a5c6', 1.0, 'COUPE', 'DIESEL', 921283, 2003);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (171, 'skoda', 'insignia', 1.4, 'SEDAN', 'DIESEL', 877712, 2008);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (172, 'audi', 'octavia', 1.4, 'STATION_WAGON', 'BENZINE', 991597, 2004);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (173, 'skoda', 'a8', 1.5, 'HATCHBACK', 'LPG', 164200, 2013);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (174, 'mercedes', 'octavia', 1.6, 'CABRIOLET', 'BENZINE', 278519, 1992);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (175, 'wolkswagen', 'f26', 1.4, 'HATCHBACK', 'DIESEL', 515018, 1996);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (176, 'audi', 'amg63', 1.6, 'SEDAN', 'DIESEL', 335428, 2012);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (177, 'mercedes', 'passat b5', 1.9, 'HATCHBACK', 'ELECTRIC', 349354, 1998);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (178, 'wolkswagen', 'arteon', 1.3, 'STATION_WAGON', 'BENZINE', 208392, 2004);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (179, 'wolkswagen', 'amg63', 1.6, 'HATCHBACK', 'DIESEL', 595527, 2012);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (180, 'mercedes', 'insignia', 1.7, 'SUV', 'LPG', 440516, 2003);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (181, 'opel', 'f26', 1.3, 'STATION_WAGON', 'LPG', 731484, 1993);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (182, 'opel', 'a4b5', 1.9, 'HATCHBACK', 'BENZINE', 435028, 2005);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (183, 'opel', 'arteon', 1.9, 'CABRIOLET', 'ELECTRIC', 86446, 2005);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (184, 'audi', 'f26', 1.1, 'CABRIOLET', 'DIESEL', 170976, 2008);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (185, 'audi', 'a7', 1.6, 'SEDAN', 'BENZINE', 256565, 2006);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (186, 'audi', 'a8', 1.9, 'STATION_WAGON', 'DIESEL', 908818, 1995);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (187, 'bmw', 'e47', 1.7, 'SEDAN', 'ELECTRIC', 728828, 2008);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (188, 'bmw', 'f26', 1.5, 'COUPE', 'LPG', 517015, 1993);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (189, 'audi', 'g62', 1.2, 'SEDAN', 'BENZINE', 203693, 1999);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (190, 'mercedes', 'arteon', 1.5, 'COUPE', 'LPG', 801952, 2008);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (191, 'opel', 'a7 avant', 1.2, 'HATCHBACK', 'LPG', 381739, 1993);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (192, 'opel', 'e47', 1.8, 'SEDAN', 'LPG', 749990, 2005);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (193, 'bmw', 'fabia', 1.2, 'SEDAN', 'LPG', 583617, 1995);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (194, 'wolkswagen', 'fabia', 1.7, 'STATION_WAGON', 'LPG', 138778, 1998);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (195, 'wolkswagen', 'a7', 1.6, 'SUV', 'BENZINE', 832618, 2003);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (196, 'skoda', 'octavia', 1.7, 'COUPE', 'BENZINE', 181727, 2010);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (197, 'wolkswagen', 'arteon', 1.2, 'SEDAN', 'BENZINE', 745848, 2008);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (198, 'mercedes', 'fabia', 1.9, 'STATION_WAGON', 'LPG', 763973, 1990);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (199, 'bmw', 'amg63', 1.7, 'HATCHBACK', 'ELECTRIC', 661671, 1998);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (200, 'opel', 'a7 avant', 1.8, 'SEDAN', 'LPG', 651324, 1998);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (201, 'bmw', 'passat b5', 1.4, 'SUV', 'DIESEL', 630451, 2011);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (202, 'wolkswagen', 'a7', 1.7, 'STATION_WAGON', 'DIESEL', 705588, 1993);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (203, 'audi', 'a5c6', 1.7, 'COUPE', 'DIESEL', 465447, 1986);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (204, 'skoda', 'g62', 1.6, 'HATCHBACK', 'LPG', 518985, 2003);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (205, 'bmw', 'octavia', 2.0, 'SUV', 'DIESEL', 148614, 2009);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (206, 'mercedes', 'a7 avant', 1.8, 'COUPE', 'ELECTRIC', 140612, 2001);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (207, 'audi', 'e36', 1.3, 'CABRIOLET', 'DIESEL', 794998, 1988);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (208, 'bmw', 'a4b7', 1.0, 'HATCHBACK', 'ELECTRIC', 84744, 2006);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (209, 'skoda', 'arteon', 1.2, 'CABRIOLET', 'DIESEL', 437743, 2005);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (210, 'mercedes', 'e47', 1.5, 'COUPE', 'LPG', 211218, 2012);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (211, 'wolkswagen', 'c63amg', 1.0, 'SEDAN', 'BENZINE', 861655, 2007);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (212, 'mercedes', 'insignia', 1.2, 'COUPE', 'LPG', 494798, 2013);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (213, 'audi', 'a8', 1.6, 'COUPE', 'DIESEL', 446448, 1991);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (214, 'bmw', 'a4b7', 1.8, 'STATION_WAGON', 'ELECTRIC', 541053, 2005);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (215, 'bmw', 'e47', 1.1, 'SUV', 'BENZINE', 358859, 1998);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (216, 'skoda', 'fabia', 1.4, 'STATION_WAGON', 'LPG', 717039, 1992);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (217, 'mercedes', 'g62', 1.1, 'SUV', 'ELECTRIC', 555003, 1999);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (218, 'audi', 'insignia', 1.8, 'SEDAN', 'BENZINE', 163075, 2007);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (219, 'skoda', 'e47', 1.0, 'HATCHBACK', 'DIESEL', 566304, 2013);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (220, 'mercedes', 'insignia', 1.4, 'COUPE', 'BENZINE', 326465, 2001);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (221, 'audi', 'amg63', 1.4, 'CABRIOLET', 'LPG', 727517, 1992);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (222, 'audi', 'f26', 1.2, 'SUV', 'DIESEL', 418970, 2004);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (223, 'bmw', 'a7 avant', 1.6, 'HATCHBACK', 'BENZINE', 347426, 2007);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (224, 'wolkswagen', 'e47', 1.7, 'COUPE', 'BENZINE', 221056, 1992);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (225, 'skoda', 'a5c6', 1.5, 'CABRIOLET', 'ELECTRIC', 588909, 2000);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (226, 'wolkswagen', 'a4b7', 2.0, 'SUV', 'ELECTRIC', 297917, 1994);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (227, 'wolkswagen', 'insignia', 1.4, 'COUPE', 'DIESEL', 960710, 2006);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (228, 'audi', 'g62', 1.3, 'SUV', 'LPG', 180572, 2008);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (229, 'skoda', 'a4b5', 1.4, 'COUPE', 'DIESEL', 230487, 1994);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (230, 'wolkswagen', 'a4b7', 1.0, 'SEDAN', 'ELECTRIC', 991564, 1993);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (231, 'bmw', 'a8', 1.9, 'COUPE', 'ELECTRIC', 362179, 2010);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (232, 'bmw', 'amg63', 1.9, 'CABRIOLET', 'DIESEL', 864743, 1987);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (233, 'wolkswagen', 'c63amg', 1.7, 'HATCHBACK', 'DIESEL', 739361, 1995);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (234, 'mercedes', 'f26', 1.3, 'STATION_WAGON', 'LPG', 198284, 2005);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (235, 'wolkswagen', 'a4b5', 1.6, 'SUV', 'BENZINE', 521775, 2012);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (236, 'mercedes', 'fabia', 1.7, 'SEDAN', 'BENZINE', 422186, 2010);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (237, 'bmw', 'e47', 1.5, 'HATCHBACK', 'BENZINE', 609618, 1999);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (238, 'opel', 'amg63', 1.7, 'SUV', 'ELECTRIC', 715124, 2000);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (239, 'audi', 'amg63', 1.4, 'STATION_WAGON', 'LPG', 229750, 2008);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (240, 'opel', 'g62', 1.1, 'COUPE', 'BENZINE', 690700, 1999);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (241, 'skoda', 'f26', 1.3, 'SEDAN', 'ELECTRIC', 946420, 1964);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (242, 'mercedes', 'e47', 1.7, 'COUPE', 'DIESEL', 130053, 2011);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (243, 'skoda', 'a5c6', 1.7, 'STATION_WAGON', 'BENZINE', 223187, 2005);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (244, 'mercedes', 'a4b7', 1.6, 'STATION_WAGON', 'BENZINE', 770249, 1998);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (245, 'bmw', 'e36', 1.0, 'HATCHBACK', 'LPG', 962490, 1992);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (246, 'opel', 'a7', 1.9, 'STATION_WAGON', 'LPG', 989392, 1992);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (247, 'wolkswagen', 'octavia', 1.7, 'HATCHBACK', 'BENZINE', 332803, 2000);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (248, 'bmw', 'f26', 1.6, 'HATCHBACK', 'ELECTRIC', 680706, 2008);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (249, 'mercedes', 'f26', 2.0, 'HATCHBACK', 'DIESEL', 283976, 1993);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (250, 'audi', 'c63amg', 1.1, 'COUPE', 'DIESEL', 237643, 1985);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (251, 'skoda', 'c63amg', 1.1, 'COUPE', 'DIESEL', 998423, 2011);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (252, 'bmw', 'arteon', 1.6, 'CABRIOLET', 'ELECTRIC', 951793, 1985);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (253, 'wolkswagen', 'amg63', 1.8, 'STATION_WAGON', 'BENZINE', 742506, 2006);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (254, 'audi', 'a4b5', 1.1, 'HATCHBACK', 'BENZINE', 444945, 2001);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (255, 'mercedes', 'e36', 1.7, 'HATCHBACK', 'ELECTRIC', 848571, 2004);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (256, 'bmw', 'e47', 1.0, 'SUV', 'BENZINE', 218523, 2012);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (257, 'mercedes', 'a8', 1.2, 'SEDAN', 'DIESEL', 340579, 2008);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (258, 'opel', 'e36', 1.7, 'COUPE', 'DIESEL', 983169, 1993);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (259, 'wolkswagen', 'a7', 1.1, 'HATCHBACK', 'DIESEL', 717457, 2004);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (260, 'wolkswagen', 'passat b5', 1.3, 'CABRIOLET', 'ELECTRIC', 875180, 1987);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (261, 'opel', 'amg63', 1.1, 'CABRIOLET', 'BENZINE', 648856, 1994);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (262, 'mercedes', 'insignia', 1.0, 'CABRIOLET', 'DIESEL', 592727, 1986);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (263, 'skoda', 'e47', 1.5, 'COUPE', 'BENZINE', 377559, 1997);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (264, 'audi', 'passat b5', 1.9, 'CABRIOLET', 'ELECTRIC', 471798, 2010);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (265, 'opel', 'arteon', 1.7, 'COUPE', 'DIESEL', 565465, 1993);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (266, 'skoda', 'e47', 1.3, 'SEDAN', 'DIESEL', 669566, 1988);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (267, 'wolkswagen', 'a7 avant', 1.5, 'COUPE', 'LPG', 466246, 1990);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (268, 'opel', 'a4b7', 1.3, 'STATION_WAGON', 'DIESEL', 188673, 1999);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (269, 'wolkswagen', 'arteon', 1.4, 'STATION_WAGON', 'ELECTRIC', 192652, 2010);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (270, 'audi', 'passat b5', 1.6, 'COUPE', 'DIESEL', 423412, 2002);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (271, 'opel', 'arteon', 1.7, 'STATION_WAGON', 'LPG', 286347, 1971);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (272, 'audi', 'arteon', 1.3, 'STATION_WAGON', 'ELECTRIC', 522027, 2009);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (273, 'skoda', 'a8', 1.5, 'HATCHBACK', 'ELECTRIC', 552997, 2010);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (274, 'mercedes', 'a4b5', 1.4, 'HATCHBACK', 'ELECTRIC', 169650, 2007);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (275, 'mercedes', 'octavia', 1.0, 'HATCHBACK', 'BENZINE', 613944, 2008);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (276, 'wolkswagen', 'passat b5', 1.9, 'SEDAN', 'LPG', 747485, 2012);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (277, 'bmw', 'g62', 1.6, 'CABRIOLET', 'LPG', 475686, 2009);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (278, 'mercedes', 'e47', 1.8, 'HATCHBACK', 'DIESEL', 830404, 2004);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (279, 'audi', 'a5c6', 1.7, 'STATION_WAGON', 'ELECTRIC', 900206, 2012);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (280, 'audi', 'a4b7', 1.0, 'HATCHBACK', 'LPG', 858785, 2000);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (281, 'bmw', 'fabia', 1.4, 'COUPE', 'LPG', 165042, 1971);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (282, 'audi', 'arteon', 1.5, 'CABRIOLET', 'LPG', 455033, 2008);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (283, 'opel', 'amg63', 1.0, 'STATION_WAGON', 'LPG', 479435, 2010);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (284, 'skoda', 'c63amg', 1.1, 'SUV', 'DIESEL', 607591, 1995);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (285, 'audi', 'arteon', 1.4, 'STATION_WAGON', 'BENZINE', 451470, 1992);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (286, 'bmw', 'passat b5', 1.8, 'SEDAN', 'ELECTRIC', 825071, 1980);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (287, 'mercedes', 'passat b5', 1.9, 'STATION_WAGON', 'BENZINE', 986555, 1984);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (288, 'opel', 'e47', 1.7, 'HATCHBACK', 'LPG', 434799, 1989);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (289, 'mercedes', 'octavia', 1.1, 'SEDAN', 'BENZINE', 966261, 2010);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (290, 'bmw', 'octavia', 1.9, 'CABRIOLET', 'LPG', 477396, 1983);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (291, 'skoda', 'a8', 1.9, 'CABRIOLET', 'LPG', 622256, 2008);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (292, 'audi', 'a7 avant', 1.8, 'CABRIOLET', 'DIESEL', 673864, 2004);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (293, 'audi', 'a8', 1.9, 'SUV', 'LPG', 687919, 2011);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (294, 'bmw', 'a8', 2.0, 'COUPE', 'LPG', 258870, 1985);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (295, 'wolkswagen', 'g62', 2.0, 'SUV', 'DIESEL', 902248, 1991);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (296, 'opel', 'e47', 1.9, 'COUPE', 'LPG', 124453, 2003);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (297, 'mercedes', 'fabia', 1.9, 'STATION_WAGON', 'BENZINE', 806791, 2003);
insert into public.cars (id, brand, model, engine_capacity, body_type, type_of_fuel, new_car_cost, production_year) values (298, 'skoda', 'e36', 1.7, 'STATION_WAGON', 'DIESEL', 804470, 2001);

